# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZeaBelleGoods', '0003_products_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
