# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZeaBelleGoods', '0009_auto_20171229_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
